pipeline {
    agent {
        kubernetes {
            label 'kaniko-git'
            defaultContainer 'kaniko'
        }
    }
        
    stages {
        stage('Build and Push') {
            steps {
                script {
                    container('kaniko') {
                        String tag = null
                        dir('todo-app') {
                            String valuesFile = 'client-values.yaml'
                            def yaml = readYaml file: valuesFile
                            tag = yaml.image.tag
                        }
                        if (tag != null) {
                            sh """
                                /kaniko/executor \
                                --context=./client \
                                --dockerfile=./client/Dockerfile \
                                --destination=volk22kaimn/todo-app-client:${tag}
                            """
                            currentBuild.displayName = "Build #${env.BUILD_NUMBER} - tag: ${tag}"
                        }
                    }
                }
            }
        }
        stage("Deploy") {
            when {
                branch 'main'
            }
            steps {
                build job: 'CD', parameters: [string(name: 'BRANCH_NAME', value: 'main'), string(name: 'APP_TO_DEPLOY', value: 'client')]
            }
        }
    }
}