replicaCount: 1
appName: todo-app-client


image:
  repository: volk22kaimn/todo-app-client
  tag: "1.0.2"

selector:
  appName: todo-app-client
 
container:
  port:
    name: http 



service:
  portName: todo-client
  port: 80
  type: NodePort
  nodePort: 32001

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

env:
  variables:
    - name: API_URL
      value: "http://134.122.84.30:30829/api/v2"

livenessProbe:
  httpGet:
    path: /
    port: 80
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10

command:
  command:
    - "/bin/sh"
  args:
    - "-c"
    - |
      echo "window._env_ = { API_URL: \"${API_URL}\" } ;" > /usr/share/nginx/html/config.js && exec nginx -g 'daemon off;'

ingress: null
networkPolicy: null

hpa:
  cpuUtilization: 70
  minReplicas: 2
  maxReplicas: 10
