replicaCount: 1
appName: todo-app-db

image:
  repository: mongo
  tag: "latest"

selector:
  appName: todo-app-db

container:
  port:
    name: http 

strategy: null

readinessProbe: null

livenessProbe:
  exec:
    command:
      - sh
      - -c
      - 'mongosh -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --quiet --eval "db.adminCommand({ ping: 1 }).ok" 2>/dev/null | grep 1 || mongo -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD" --authenticationDatabase admin --quiet --eval "db.adminCommand({ ping: 1 }).ok" | grep 1'
  initialDelaySeconds: 15
  periodSeconds: 10

service:
  portName: mongodb
  port: 27017
  type: ClusterIP

envFrom:
  - secretRef:
      name: mongo-root
  

networkPolicy:
  name: mongodb-network-policy
  namespace: todo
  toPodLabels:
    - key: appName
      value: todo-app-db
  fromPodLabels: 
    - key: appName
      value: todo-app-server

ingress: null
