replicaCount: 1
appName: todo-app-db

image:
  repository: mongo
  tag: "latest"

selector:
  appName: todo-app-db

container:
  port:
    name: http 


strategy:
  enabled: false

readinessProbe:
  enabled: false

livenessProbe:
  enabled: true
  type: exec
  command:
    - sh
    - -c
    - 'mongosh --quiet --eval "db.adminCommand({ ping: 1 }).ok" 2>/dev/null | grep 1 || mongo --quiet --eval "db.adminCommand({ ping: 1 }).ok" | grep 1'
  initialDelaySeconds: 15
  periodSeconds: 10

service:
  portName: mongodb
  port: 27017
  type: ClusterIP

env: 
  enabled: false

command:
  enabled: false
  

networkPolicy:
  enabled: true
  name: mongodb-network-policy
  namespace: todo
  toPodLabels:
    - key: appName
      value: todo-app-db
  fromPodLabels: 
    - key: appName
      value: todo-app-server


ingress:
  enabled: false
