replicaCount: 1
appName: todo-app-server


image:
  repository: volk22kaimn/todo-app-server
  tag: "1.0.1"

selector:
  appName: todo-app-server

container:
  port:
    name: http 

readinessProbe:
  httpGet:
    path: /health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /health
    port: 3000
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10

service:
  portName: todo-server
  port: 3000
  type: NodePort
  nodePort: 30829

env: null
  # variables:
  # - name: MONGODB_URI
  #   valueFrom:
  #     secretKeyRef:
  #       name: mongo-app
  #       key: MONGODB_URI



networkPolicy: null
  

ingress: null
