replicaCount: 1
appName: todo-app-server


image:
  repository: volk22kaimn/todo-app-server
  tag: "1.0.1"

selector:
  appName: todo-app-server

container:
  port:
    name: http 

readinessProbe:
  enabled: true
  path: /health
  port: 3000
  initialDelaySeconds: 5
  periodSeconds: 5


service:
  portName: todo-server
  port: 3000
  type: NodePort
  nodePort: 30829

env: 
  enabled: true
  variables:
  - name: MONGODB_URI
    value: mongodb://todo-app-db-green:27017/todoapp

command:
  enabled: false

networkPolicy:
  enabled: false
  

ingress:
  enabled: false
