{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}-{{ .Values.environment }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      {{- range .Values.networkPolicy.toPodLabels }}
      {{ .key }}: {{ printf "%s-%s" .value $.Values.environment }}
      {{- end }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- range .Values.networkPolicy.fromPodLabels }}
          {{ .key }}: {{ printf "%s-%s" .value $.Values.environment }}
          {{- end }}
{{- end }}